### ISSUE TITLE
Can't build with ESP32-C6 IDF 5.4.1

### ISSUE THREAD

**Issue by trianglesis** [nopnop2002/esp32-idf-sqlite3#5]
Added by using dependencies yaml
I'm using ESP 32 C6 nano with LP core.

```yaml
## IDF Component Manager Manifest File
dependencies:
  ## Required IDF version
  idf:
    version: '>=4.1.0'
  # # Put list of dependencies here
  # # For components maintained by Espressif:
  # component: "~1.0.0"
  # # For 3rd party components:
  # username/component: ">=1.0.0,<2.0.0"
  # username2/component2:
  #   version: "~1.0.0"
  #   # For transient dependencies `public` flag can be set.
  #   # `public` flag doesn't have an effect dependencies of the `main` component.
  #   # All dependencies of `main` are public by default.
  #   public: true
  lvgl/lvgl: ^9.2.2
  joltwallet/littlefs: ^1.19.2
  espressif/led_strip: ^3.0.1
  nopnop2002/sqlite3:
    path: components/esp32-idf-sqlite3/
    git: https://github.com/nopnop2002/esp32-idf-sqlite3.git
```

`riscv32-esp-elf-gcc.exe: error: unrecognized command-line option '-mlongcalls'`

There is such an arg in CMakeLists:

```cmake
target_compile_options(${COMPONENT_LIB} PRIVATE -std=gnu99 -g3 -fno-stack-protector -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -mlongcalls -nostdlib -Wpointer-arith -Wno-error=unused-value -Wno-error=unused-label -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wno-error=char-subscripts -Wno-error=maybe-uninitialized -Wno-unused-parameter -Wno-sign-compare -Wno-old-style-declaration -Wno-cast-function-type -Wno-unused-function -Wno-unused-variable -Wno-implicit-fallthrough -Wno-unused-but-set-variable -Wno-extra -Wno-char-subscripts -Wno-unused-label -Wno-unused-value -MMD -c -DF_CPU=240000000L -DESP32 -DCORE_DEBUG_LEVEL=0 -DNDEBUG)
```

There are a lot of popups with `esphome` errors, too.

`StdErr:'esphome' is not recognized as an internal or external command,
operable program or batch file.`

![Image](https://github.com/user-attachments/assets/f37b15ab-c37c-4099-8072-c227005c86b0)

**Comment by trianglesis** [comment]
I'm unfamiliar with the `mlongcalls` directive, but removing it can build just fine.
Maybe I'll try to use it without this one to see the impact later.

**Comment by nopnop2002** [comment]
I built it using this idf_component.yml and there were no errors.

```
dependencies:
  lvgl/lvgl: ^9.2.2
  joltwallet/littlefs: ^1.19.2
  espressif/led_strip: ^3.0.1
  nopnop2002/sqlite3:
    path: components/esp32-idf-sqlite3/
    git: https://github.com/nopnop2002/esp32-idf-sqlite3.git
```

My main.c is this.
```
#include <stdio.h>
#include <inttypes.h>
#include <string.h>

void app_main(void)
{
    int value = 100;
    printf("value=%d\n", value);
}
```

Is there a problem with your main.c?

**Comment by trianglesis** [comment]
> This may indicate a problem with your esphome.

It's probably unrelated.

But the build worked fine when I removed the `mlongcalls` arg.

**Comment by nopnop2002** [comment]
Details of the compilation options are published here.

mlongcalls is also mentioned, but it is difficult to understand.

https://gcc.gnu.org/onlinedocs/gcc/Xtensa-Options.html

**Comment by trianglesis** [comment]
I've reinstalled IDF completely and started the build again.

The issue is still there: `riscv32-esp-elf-gcc.exe: error: unrecognized command-line option '-mlongcalls'`


```log
[905/1464] Building C object esp-idf/nopnop2002__sqlite3/CMakeFiles/__idf_nopnop2002__sqlite3.dir/sqlite3.c.obj
FAILED: esp-idf/nopnop2002__sqlite3/CMakeFiles/__idf_nopnop2002__sqlite3.dir/sqlite3.c.obj
E:\ESP_IDF\tools\riscv32-esp-elf\esp-14.2.0_20241119\riscv32-esp-elf\bin\riscv32-esp-elf-gcc.exe -DESP_PLATFORM -DIDF_VER=\"v5.4.1\" -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DSOC_MMU_PAGE_SIZE=CONFIG_MMU_PAGE_SIZE -DSOC_XTAL_FREQ_MHZ=CONFIG_XTAL_FREQ -D_GLIBCXX_HAVE_POSIX_SEMAPHORE -D_GLIBCXX_USE_POSIX_SEMAPHORE -D_GNU_SOURCE -D_POSIX_READER_WRITER_LOCKS -ID:/Projects/ESP/ESP32-C6/AQS-Indoor/build/config -ID:/Projects/ESP/ESP32-C6/AQS-Indoor/managed_components/nopnop2002__sqlite3/include -ID:/Projects/ESP/ESP32-C6/AQS-Indoor/managed_components/nopnop2002__sqlite3/private_include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/newlib/platform_include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/freertos/config/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/freertos/config/include/freertos -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/freertos/config/riscv/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/freertos/FreeRTOS-Kernel/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/include/freertos -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/freertos/esp_additions/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/esp_hw_support/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/esp_hw_support/include/soc -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/esp_hw_support/include/soc/esp32c6 -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/esp_hw_support/dma/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/esp_hw_support/ldo/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/esp_hw_support/debug_probe/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/esp_hw_support/port/esp32c6/. -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/esp_hw_support/port/esp32c6/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/esp_hw_support/port/esp32c6/private_include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/heap/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/heap/tlsf -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/log/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/soc/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/soc/esp32c6 -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/soc/esp32c6/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/soc/esp32c6/register -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/hal/platform_port/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/hal/esp32c6/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/hal/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/esp_rom/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/esp_rom/esp32c6/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/esp_rom/esp32c6/include/esp32c6 -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/esp_rom/esp32c6 -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/esp_common/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/esp_system/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/esp_system/port/soc -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/esp_system/port/include/riscv -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/esp_system/port/include/private -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/riscv/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/lwip/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/lwip/include/apps -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/lwip/include/apps/sntp -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/lwip/lwip/src/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/lwip/port/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/lwip/port/freertos/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/lwip/port/esp32xx/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/lwip/port/esp32xx/include/arch -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/lwip/port/esp32xx/include/sys -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/mbedtls/port/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/mbedtls/mbedtls/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/mbedtls/mbedtls/library -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/mbedtls/esp_crt_bundle/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/mbedtls/mbedtls/3rdparty/everest/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/mbedtls/mbedtls/3rdparty/p256-m -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/mbedtls/mbedtls/3rdparty/p256-m/p256-m -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/console -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/vfs/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/esp_vfs_console/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/spiffs/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/esp_partition/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/spi_flash/include -IE:/ESP_IDF/esp/v5.4.1/esp-idf/components/esp_timer/include -march=rv32imac_zicsr_zifencei  -fdiagnostics-color=always -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=unused-but-set-variable -Wno-error=deprecated-declarations -Wextra -Wno-error=extra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion -gdwarf-4 -ggdb -nostartfiles -Og -fno-shrink-wrap -fmacro-prefix-map=D:/Projects/ESP/ESP32-C6/AQS-Indoor=. -fmacro-prefix-map=E:/ESP_IDF/esp/v5.4.1/esp-idf=/IDF -fstrict-volatile-bitfields -fno-jump-tables -fno-tree-switch-conversion -std=gnu17 -Wno-old-style-declaration -std=gnu99 -g3 -fno-stack-protector -mlongcalls -nostdlib -Wpointer-arith -Wno-error=unused-value -Wno-error=unused-label -Wno-error=char-subscripts -Wno-error=maybe-uninitialized -Wno-cast-function-type -Wno-unused-function -Wno-unused-variable -Wno-implicit-fallthrough -Wno-unused-but-set-variable -Wno-extra -Wno-char-subscripts -Wno-unused-label -Wno-unused-value -MMD -c -DF_CPU=240000000L -DESP32 -DCORE_DEBUG_LEVEL=0 -DNDEBUG -MD -MT esp-idf/nopnop2002__sqlite3/CMakeFiles/__idf_nopnop2002__sqlite3.dir/sqlite3.c.obj -MF esp-idf\nopnop2002__sqlite3\CMakeFiles\__idf_nopnop2002__sqlite3.dir\sqlite3.c.obj.d -o esp-idf/nopnop2002__sqlite3/CMakeFiles/__idf_nopnop2002__sqlite3.dir/sqlite3.c.obj -c D:/Projects/ESP/ESP32-C6/AQS-Indoor/managed_components/nopnop2002__sqlite3/sqlite3.c
riscv32-esp-elf-gcc.exe: error: unrecognized command-line option '-mlongcalls'
```

**Comment by nopnop2002** [comment]
After looking at your logging, I found the cause.

There are XTENSA and RISCV for ESP32, but it seems that the -mlongcalls compile option cannot be used with the RISCV compiler.

This has been fixed in the latest version.

https://github.com/nopnop2002/esp32-idf-sqlite3/commit/a27228d70b9bcf92149a28e7ea490661f9a9ca4d

Thank you for reporting it.

**Comment by trianglesis** [comment]
Something dumb is happening, but I can't get the latest version:

```
  nopnop2002/sqlite3:
    version: main
    path: components/esp32-idf-sqlite3/
    git: https://github.com/nopnop2002/esp32-idf-sqlite3.git
```

With or without `version: main`, I'm still getting the cMake file with `'-mlongcalls'`
